name: Build, Test, and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security_tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: clone the GitHub repo on the machine
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install program dependencies
      run: npm ci

    - name: Run intesecurity tests
      run: npm audit

  build_test:
    runs-on: ubuntu-latest
    needs: security_tests 

    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: clone the GitHub repo on the machine
      uses: actions/checkout@v4

    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'

    - name: Install program dependencies
      run: npm ci

    - name: Start the app
      run: npm run start &

    - name: Run integration test
      run: npm run test
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.SERVICE_ID }}
          api_key: ${{ secrets.RENDER_TOKEN }}
          wait_deploy: true 
